#!/usr/bin/env python3
"""
PlatformIO pre-build script: gzip-compress HTML pages and generate C header files.

Source HTML files live in:  html/*.html
Generated .h files go to:   lib/htmlFiles/*.h

Each .h file contains a uint8_t array with the gzip-compressed page data,
plus a size_t constant. WebRoutes.cpp must serve these with:
  Content-Encoding: gzip
  Content-Type:     text/html
  Cache-Control:    max-age=3600
"""

import gzip
import os

Import("env")  # noqa: F821 – PlatformIO SConstruct environment

PROJECT_DIR = env.subst("$PROJECT_DIR")  # noqa: F821

PAGES = [
    {
        "html":   "html/index.html",
        "header": "lib/htmlFiles/indexPage.h",
        "guard":  "INDEX_PAGE_h",
        "var":    "indexPage",
    },
    {
        "html":   "html/zone-settings.html",
        "header": "lib/htmlFiles/zoneSettingsPage.h",
        "guard":  "ZONE_SETTINGS_PAGE_h",
        "var":    "zoneSettingsPage",
    },
    {
        "html":   "html/service-settings.html",
        "header": "lib/htmlFiles/serviceSettingsPage.h",
        "guard":  "SERVICE_SETTINGS_PAGE_h",
        "var":    "serviceSettingsPage",
    },
    {
        "html":   "html/ota.html",
        "header": "lib/htmlFiles/otaPage.h",
        "guard":  "OTA_PAGE_h",
        "var":    "otaPage",
    },
    {
        "html":   "html/backup.html",
        "header": "lib/htmlFiles/backupPage.h",
        "guard":  "BACKUP_PAGE_h",
        "var":    "backupPage",
    },
]


def generate_header(html_path, header_path, guard, var_name):
    abs_html   = os.path.join(PROJECT_DIR, html_path)
    abs_header = os.path.join(PROJECT_DIR, header_path)

    if not os.path.exists(abs_html):
        print("[build_html] WARNING: {} not found, skipping.".format(html_path))
        return

    with open(abs_html, "rb") as f:
        raw = f.read()
    compressed = gzip.compress(raw, compresslevel=9)

    # Format as C byte array (16 bytes per line)
    lines = []
    chunk = []
    for b in compressed:
        chunk.append("0x{:02x}".format(b))
        if len(chunk) == 16:
            lines.append("    " + ", ".join(chunk) + ",")
            chunk = []
    if chunk:
        lines.append("    " + ", ".join(chunk))
    array_content = "\n".join(lines)

    header_content = (
        "#ifndef {guard}\n"
        "#define {guard}\n\n"
        "#include <Arduino.h>\n\n"
        "// Auto-generated by tools/build_html.py - do NOT edit manually.\n"
        "// Source: {html}\n"
        "// Original: {raw_len} bytes  Compressed: {gz_len} bytes\n\n"
        "const uint8_t {var}[] PROGMEM = {{\n"
        "{content}\n"
        "}};\n"
        "const size_t {var}_len = {gz_len};\n\n"
        "#endif\n"
    ).format(
        guard=guard,
        html=html_path,
        raw_len=len(raw),
        gz_len=len(compressed),
        var=var_name,
        content=array_content,
    )

    os.makedirs(os.path.dirname(abs_header), exist_ok=True)
    with open(abs_header, "w") as f:
        f.write(header_content)

    pct = len(compressed) / len(raw) * 100
    print("[build_html] {} -> {}  {} -> {} bytes ({:.0f}%)".format(
        html_path, header_path, len(raw), len(compressed), pct))


# Run immediately at script load time (before any compilation)
print("[build_html] Compressing HTML pages...")
for page in PAGES:
    generate_header(page["html"], page["header"], page["guard"], page["var"])
print("[build_html] Done.")
